INSERT INTO clinical_note (vista_ien, title) VALUES ('8', 'ADVANCE DIRECTIVE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1632', 'ADVANCE DIRECTIVE COMPLETED');
INSERT INTO clinical_note (vista_ien, title) VALUES ('20', 'CRISIS NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('117', 'CRISIS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('15', 'CLINICAL WARNING');
INSERT INTO clinical_note (vista_ien, title) VALUES ('832', 'FALL RISK');
INSERT INTO clinical_note (vista_ien, title) VALUES ('833', 'OUTSIDE MEDICATION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('17', 'Adverse React/Allergy');
INSERT INTO clinical_note (vista_ien, title) VALUES ('40', 'ASI-ADDICTION SEVERITY INDEX');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1390', 'VISUAL IMPAIRMENT MEDICAL EXAM');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1391', 'VISUAL IMPAIRMENT CLINIC INITIAL VISIT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('116', 'NURSING NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1649', 'NURSING SURGICAL EVALUATION UNIT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1650', 'MEDICATION RECONCILIATION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1651', 'NURSING PREOP ASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1652', 'PROCEDURE PATIENT SITE VERIFICATION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1653', 'NURSING ADMISSION ASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1654', 'NURSING REASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1655', 'NURSING DISCHARGE INSTRUCTIONS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('134', 'H&P');
INSERT INTO clinical_note (vista_ien, title) VALUES ('125', 'SURGERY NOTES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('126', 'RECOVERY ROOM');
INSERT INTO clinical_note (vista_ien, title) VALUES ('819', 'NF PREOP/HOLDING ASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1656', 'INFORMED CONSENT ');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1657', 'GENERAL SURGERY RESIDENT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1658', 'ANESTHESIA PREOP ASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1659', 'ANESTHESIA POSTOP ASSESSMENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1660', 'ATTENDING NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('123', 'PATIENT TRAINING');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1405', 'DISCLOSURE OF ADVERSE EVENT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('5', 'MOVE! CLINIC VISIT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1891', 'MENTAL HEALTH DIAGNOSTIC STUDY NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('163', 'LYMPHOMA');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1617', 'CARE COORDINATION HOME TELEHEALTH SCREENING CONSULT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1627', 'DIABETIC RETINOPATHY SURVEILLANCE CONSULT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1628', 'DIABETIC TELERETINAL IMAGING CONSULT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1630', 'OPHTHALMOLOGIST CONSULT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1631', 'GENERIC CONSULT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1637', 'VEHU IMAGING CONSULT RESULT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1889', 'MENTAL HEALTH CONSULT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('826', 'INTERDISCIPLINARY INITIAL PHYSICIAN ASSESSMENT PLAN');
INSERT INTO clinical_note (vista_ien, title) VALUES ('822', 'INTERDISCIPLINARY PLAN-CARE MANAGEMENT (M)');
INSERT INTO clinical_note (vista_ien, title) VALUES ('823', 'INTERDISCIPLINARY PLAN-NURSING (M)');
INSERT INTO clinical_note (vista_ien, title) VALUES ('824', 'INTERDISCIPLINARY PLAN-NUTRITION (M)');
INSERT INTO clinical_note (vista_ien, title) VALUES ('825', 'INTERDISCIPLINARY PLAN-SOCIAL WORK (M)');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1259', 'HYPERTENSION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1633', 'CARDIOLOGY NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1634', 'DERMATOLOGY NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1635', 'OPHTHALMOLOGY NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('4', 'HOMELESS CALL CENTER REFERRAL NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('6', 'GI CLINIC NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('16', 'PRIMARY CARE VISIT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('18', 'PRIMARY CARE TELEPHONE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('22', 'PRIMARY CARE GENERAL NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1267', 'TRANSITIONAL PHARMACY BENEFIT NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1293', 'C&P EXAMINATION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1294', 'C&P MULTIPLE EXAM');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1295', 'C&P ACROMEGALY');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1296', 'C&P AID AND ATTENDANCE OR HOUSEBOUND EXAM');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1297', 'C&P ARRHYTHMIAS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1298', 'C&P ARTERIES, VEINS AND MISC');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1299', 'C&P AUDIO');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1300', 'C&P BONES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1301', 'C&P BRAIN AND SPINAL CORD');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1302', 'C&P CHRONIC FATIGUE SYNDROME');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1303', 'C&P COLD INJURY PROTOCOL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1304', 'C&P CRANIAL NERVES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1305', 'C&P CUSHING''S SYNDROME');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1306', 'C&P DENTAL AND ORAL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1307', 'C&P DIABETES MELLITUS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1308', 'C&P DIGESTIVE CONDITIONS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1309', 'C&P EAR DISEASE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1310', 'C&P EATING DISORDERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1311', 'C&P ENDOCRINE DISEASES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1312', 'C&P EPILEPSY AND NARCOLEPSY');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1313', 'C&P ESOPHAGUS AND HIATAL HERNIA');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1314', 'C&P EYE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1315', 'C&P FEET');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1316', 'C&P FIBROMYALGIA');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1317', 'C&P GENERAL MEDICAL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1318', 'C&P GENITOURINARY');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1319', 'C&P GULF WAR PROTOCOL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1320', 'C&P GYNECOLOGICAL CONDITIONS AND DISORDERS OF THE BREAST');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1321', 'C&P HAND, THUMB AND FINGERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1322', 'C&P HEART');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1323', 'C&P HEMIC DISORDERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1324', 'C&P HIV-RELATED ILLNESS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1325', 'C&P HYPERTENSION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1326', 'C&P INFECTIOUS, IMMUNE AND NUTRITIONAL DISABILITIES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1327', 'C&P INTESTINES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1328', 'C&P JOINTS (SHOULDER, ELBOW, WRIST, HIP, KNEE, ANKLE)');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1329', 'C&P LIVER, GALL BLADDER, AND PANCREAS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1330', 'C&P LYMPHATIC DISORDERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1331', 'C&P MENTAL DISORDERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1332', 'C&P MOUTH, LIPS, AND TONGUE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1333', 'C&P MUSCLES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1334', 'C&P NEUROLOGICAL DISORDERS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1335', 'C&P NOSE, SINUS, LARYNX, AND PHARYNX');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1336', 'C&P PERIPHERAL NERVES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1337', 'C&P PRISONER OF WAR PROTOCOL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1338', 'C&P PTSD, INITIAL EVALUATION');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1339', 'C&P PTSD, REVIEW');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1340', 'C&P PULMONARY TUBERCULOSIS AND MYCOBACTERIAL DISEASES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1341', 'C&P RECTUM AND ANUS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1342', 'C&P RESIDUALS OF AMPUTATIONS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1343', 'C&P RESPIRATORY');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1344', 'C&P SCARS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1345', 'C&P SENSE OF SMELL AND TASTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1346', 'C&P SKIN DISEASES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1347', 'C&P SPINE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1348', 'C&P STOMACH, DUODENUM, AND PERITONEAL ADHESIONS');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1349', 'C&P THYROID AND PARATHYROID DISEASES');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1353', 'PATIENT RECORD FLAG CATEGORY II - RISK, FALL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1354', 'PATIENT RECORD FLAG CATEGORY II - RISK, WANDERING');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1355', 'PATIENT RECORD FLAG CATEGORY II - RESEARCH STUDY');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1356', 'PATIENT RECORD FLAG CATEGORY II - INFECTIOUS DISEASE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1364', 'SCI FUNCTIONAL INDEPENDENCE MEASURE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1365', 'SCI GENERAL NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1366', 'SCI CRAIG HANDICAP ASSESSMENT&REPORTING TECHNIQUE-SHORT FORM');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1367', 'SCI DIENER SATISFACTION WITH LIFE SCALE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1387', 'IMED CONSENT');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1388', 'IMED GENERAL');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1619', 'CARE COORDINATION HOME TELEHEALTH DISCHARGE NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1620', 'CARE COORDINATION HOME TELEHEALTH EDUCATION NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1621', 'CARE COORDINATION HOME TELEHEALTH EVALUATION NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1622', 'CARE COORDINATION HOME TELEHEALTH EVALUATION TREATMENT PLAN');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1623', 'CARE COORDINATION HOME TELEHEALTH SUBSEQUENT EVAL NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1624', 'CARE COORDINATION HOME TELEHEALTH SUMMARY OF EPISODE NOTE');
INSERT INTO clinical_note (vista_ien, title) VALUES ('1625', 'CARE COORDINATION HOME TELEHEALTH TELEPHONE ENCOUNTER NOTE');
-- INSERT INTO clinical_note (vista_ien, title) VALUES ('1626', 'CARE COORDINATION HOME TELEHEALTH VIDEO VISIT NOTE');
-- INSERT INTO clinical_note (vista_ien, title) VALUES ('1669', 'MEDICATION RECONCILIATION NOTE');
-- INSERT INTO clinical_note (vista_ien, title) VALUES ('9', 'DIETICIAN CONSULT NOTE');
